In [ ]:
#################################### formats the pgp survey for machine learning ################################

In [1]:
import numpy as np
import pandas as pd

In [50]:
# load the pgp names as numpy array
names = np.load("C:\\Users\\j\\Desktop\\tiling_rep\\names14.npy") 

# load pgp array to a list
names_lst = np.ndarray.tolist(names)

# load the pgp genomes as numpy array
pgp = np.load("C:\\Users\\j\\Desktop\\tiling_rep\\hiq-pgp14")

# loads pgp info to reduce number of tiles
justVarPaths = np.load("C:\\Users\\j\\Desktop\\tiling_rep\\hiq-pgp-info14")

In [17]:
# loads the survey from sql database to be transformed into a dataframe
# courtesy of Sarah Zaranek

import sqlite3

conn = sqlite3.connect("C://Users//j//Desktop//tiling_rep//untap.db")
c = conn.cursor()
c.execute('SELECT * FROM demographics')
rows = c.fetchall()
columns = [(i[0]) for i in c.description]
data = pd.DataFrame(rows,columns=columns)
conn.close()

In [27]:
# clean the data
        
df = data[['human_id','gender']]
df = df[df.gender != ""]
df['human_id'] = df['human_id'].apply(lambda x: x.lower())
df['gender_bnry'] = df['gender'].str.contains('Male',na=False).astype(int) #elegant solution borrowed from Sarah

df

      human_id  gender  gender_bnry
0     hu43860c    Male            1
1     huc30901    Male            1
2     hu9385ba    Male            1
3     hu04fd18    Male            1
4     huae6220    Male            1
5     hu604d39    Male            1
6     hu6e4515    Male            1
7     hua90ce6    Male            1
9     hu2fec01    Male            1
11    hu2dbf2d    Male            1
12    hu342a08  Female            0
14    hu72a81d  Female            0
15    hu0e64a1    Male            1
16    hu3cab43    Male            1
17    hu2d6140  Female            0
18    hua0e089  Female            0
19    hu8229ae  Female            0
20    huca017e    Male            1
21    hu92c40a  Female            0
22    hu38168c  Female            0
23    hub1fd55    Male            1
24    hud81f3d    Male            1
25    hud37d14  Female            0
26    hubaac98    Male            1
28    huec6eec  Female            0
29    huf5e0b6    Male            1
30    huaeadc0    Male            1
31    hu241dea    Male            1
32    hu025cea  Female            0
34    hu050e9c    Male            1
...        ...     ...          ...
1272  hu606b0a  Female            0
1273  huf297dd    Male            1
1275  hue86317    Male            1
1278  hu28f39c    Male            1
1279  hu75beff  Female            0
1280  hu88d1fc    Male            1
1281  hu34bb8e    Male            1
1282  hu3be6ef    Male            1
1284  hu4c0a4f    Male            1
1285  hu394092    Male            1
1286  huaf3c63  Female            0
1287  huda52d5  Female            0
1288  hu165e62    Male            1
1289  hu639d02    Male            1
1290  hu66330e    Male            1
1294  hu4a6650    Male            1
1295  hu594129    Male            1
1297  hu7d6ab1  Female            0
1298  hufec65a    Male            1
1300  huf9c3ee    Male            1
1304  hu039674    Male            1
1305  hu941a10  Female            0
1306  hu1d278b    Male            1
1311  hu631d32    Male            1
1312  hu934217    Male            1
1313  hu524b5b  Female            0
1314  hu78e6a9  Female            0
1316  hu313a20    Male            1
1317  hufbd57f    Male            1
1318  huc5203c  Female            0

[963 rows x 3 columns]

In [37]:
# formats a single tile by cleaning the name to make it more readable

def format(npint):
    s = ""
    string = str(npint)
    for char in range(len(string)):
        if string[char] == "-":
            break
        elif string[char] != "b" and string[char] != "'":
            s += string[char]
    return s.lower()

# runs formatting on all names

def formatall():
    tiled_partic = [] 
    for i in range(len(names_lst)):
        tiled_partic.append(format(names_lst[i]))
    return tiled_partic

In [40]:
#list of all the tiled names
tiled_names = pd.DataFrame(formatall(),columns=['human_id'])

tiled_names['human_id'] = tiled_names['human_id']

In [41]:
# keeps only the participants we have tiled genomes for

df2 =  tiled_names.merge(df,left_on = 'human_id', right_on='human_id', how='inner')

df2

     human_id  gender  gender_bnry
0    hu016b28    Male            1
1    hu025cea  Female            0
2    hu040c0a    Male            1
3    hu04df3c  Female            0
4    hu04f220  Female            0
5    hu04fd18    Male            1
6    hu050e9c    Male            1
7    hu05fd49    Male            1
8    hu089792  Female            0
9    hu0a4518    Male            1
10   hu0cf2ee    Male            1
11   hu0d1fa1  Female            0
12   hu0e64a1    Male            1
13   hu1187ff  Female            0
14   hu132b5c  Female            0
15   hu19c09f    Male            1
16   hu1e868d  Female            0
17   hu241dea    Male            1
18   hu259ac7    Male            1
19   hu26b551  Female            0
20   hu27fd1f  Female            0
21   hu297562    Male            1
22   hu2c1d94    Male            1
23   hu2d6140  Female            0
24   hu2dbf2d    Male            1
25   hu2fec01    Male            1
26   hu33e2d9    Male            1
27   hu342a08  Female            0
28   hu38168c  Female            0
29   hu3cab43    Male            1
..        ...     ...          ...
88   huba30d4    Male            1
89   hubaac98    Male            1
90   huc14ae1    Male            1
91   huc30901    Male            1
92   huc92bc9    Male            1
93   huca017e    Male            1
94   hucbdc6d    Male            1
95   hucd380f  Female            0
96   hud09534  Female            0
97   hud10e53    Male            1
98   hud37d14  Female            0
99   hud81f3d    Male            1
100  hudbd591    Male            1
101  hudbf9dd    Male            1
102  hude435d    Male            1
103  hudf04cc  Female            0
104  hue2e371    Male            1
105  hue58004  Female            0
106  huea4ee5    Male            1
107  huebd467    Male            1
108  huec6eec  Female            0
109  huf160aa    Male            1
110  huf2da6f    Male            1
111  huf5ad12    Male            1
112  huf5e0b6    Male            1
113  huf80f84  Female            0
114  huf83462  Female            0
115  hufcc1c1  Female            0
116  hufe71f3    Male            1
117  huffad87    Male            1

[118 rows x 3 columns]

In [69]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

df2['gender'].value_counts()

Male      78
Female    40
Name: gender, dtype: int64

In [51]:
survey_names = []

df2['human_id'].apply(lambda x: survey_names.append(x))

print(len(survey_names))

118

In [52]:
# keeps only the particpants of the disease survey from the pgp array and
# discards the rest

pgp_filtered = []
pgp_filtered = []
for i in range(len(pgp)):
    if format(names[i]) in survey_names:
        pgp_filtered.append(pgp[i])
        name_list.append(format(names[i]))
    else:
        pass
    
pgp_filtered = np.asarray(filtered_pgp)

pgp_filtered.shape

(118, 2564734)

In [53]:
# insert row condition here to test
condition = "gender_bnry"

X = pgp_filtered
y = df2[condition]

print(X.shape)

print(y.shape)

(118, 2564734)
(118,)

In [54]:
# Remove tiles (columns) that don't have more than 1 tile varient at every position
# Courtesy of Sarah Zaranek

min_indicator = np.amin(X, axis=0)
max_indicator = np.amax(X, axis=0)

sameTile = min_indicator == max_indicator
skipTile = ~sameTile

X = X[:,skipTile]
justVarPathsNew = justVarPaths[skipTile]

X.shape

(118, 1424194)

In [55]:
# Scale the data
from sklearn import preprocessing
pgp_filtered = preprocessing.scale(pgp_filtered.astype('double')) # scale the data

In [90]:
#################################### Linear SVC Classifier  ######################################################

from sklearn import svm
from sklearn.svm import LinearSVC 

# set the c score here
cv = 0.001 # 0.05:1.0, 
#.001

svc_test = LinearSVC(penalty='l1', class_weight='balanced', C=cv, dual=False)

In [91]:
##############################    KFold cross validation    ##################################

from sklearn.model_selection import cross_val_score, train_test_split, KFold
from sklearn.metrics import accuracy_score, confusion_matrix
 
    
# Enter Number of Splits
splits =8
kf = KFold(n_splits=splits, random_state=None, shuffle=False)
    
scoresk = []
predictedk = []
testedk = []
    
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    svc_test.fit(X_train, y_train.ravel())
    y_pred = svc_test.predict(X_test)
    scoresk.append(accuracy_score(y_test, y_pred))
    
    predictedk.append(y_pred)
    testedk.append(y_test)
    
    
print(np.mean(np.asarray(scoresk)))

acc = np.mean(np.asarray(scoresk))

0.33869047619

In [92]:
nonzeroes = np.nonzero(svc_test.coef_[0])[0]
coefs = zip(nonzeroes, svc_test.coef_[0][nonzeroes])
print(svc_test)

LinearSVC(C=0.001, class_weight='balanced', dual=False, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l1', random_state=None, tol=0.0001,
     verbose=0)

In [93]:
# sort the coefficients by their value, instead of index

coefs = sorted(coefs, key = lambda x: x[1], reverse=True)

coef_lst = []

for coef in coefs:
    print("#",coef, cv, acc)
    coef_lst.append(coef)

In [ ]:
# results

# (1419145, 0.045050109269450106), 0.05, 0.72
# (6771, 0.038682316909352685), 0.05, 0.72
# (778301, 0.031860055548773476), 0.05, 0.72

# (823707, 0.067399100314026933) 0.09 0.645833333333
# (1089816, 0.047275442069083726) 0.09 0.645833333333
# (6771, 0.034411025407538952) 0.09 0.645833333333

# (1419145, 0.039059860959711444) 0.03 0.720238095238
# (6771, 0.036776833494964058) 0.03 0.720238095238
# (1089816, 0.032398320317830284) 0.03 0.720238095238

# (1419145, 0.033134475981882662) 0.01 0.618452380952
# (778301, 0.023112465317369012) 0.01 0.618452380952
# (1089816, 0.021717502097486102) 0.01 0.618452380952